# -*- coding: utf-8 -*-
"""gaussSeidel

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vPuRNpJxDrioJ1eWuPnqD9Hnc-LsBev4

**Método de Gauss Seidel**
"""

def norma(v,x):

  n = len(v)
  maxnum = 0
  maxden = 0
  for i in range(0, n):
    num = abs(v[i] - x[i])
    if num > maxnum:
      maxnum = num
    
    den = abs(v[i])
    if den > maxden:
      maxden = den

  return maxnum/maxden

def seidel (A, b, e, iteracao=10):

  n = len(A)
  v = n*[0]
  x = n*[0]

  for i in range(0, n):
    for j in range(0, n):
      if i != j:
        A[i][j] = A[i][j]/A[i][i]
    b[i] = b[i]/A[i][i]
   

  for k in range(1, iteracao):
    for i in range(0, n):
      soma = 0
      for j in range(0, n):
        if i != j:
          soma = soma + A[i][j] * x[j]
      
      x[i] = b[i] - soma
    d = norma(x, v)
    if d <= e:
      return x

    for i in range(0, n):
      v[i] = x[i]

A = [[10, 2, 1],
     [1, 5, 1],
     [2, 3, 10]]

b = [7, -8, 6]

e = 0.05

x = seidel(A, b, e)
print(x)

A = [[5,1,1],
     [3,4,1],
     [3,3,6]]

b = [5, 6, 0]

e = 0.05

x = seidel(A, b, e)
print(x)