# -*- coding: utf-8 -*-
"""gaussJacobi

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/176mFUWUAQrSEAo4676wixXBlxNxvS6_d

**Método de Gauss-Jacobi**
"""

def norma(v,x):

  n = len(v)
  maxnum = 0
  maxden = 0
  for i in range(0, n):
    num = abs(v[i] - x[i])
    if num > maxnum:
      maxnum = num
    
    den = abs(v[i])
    if den > maxden:
      maxden = den

  return maxnum/maxden

def jacobi (A, b, e, iteracao=10):

  n = len(A)
  v = n*[0]
  x = n*[0]

  for i in range(0, n):
    for j in range(0, n):
      if i != j:
        A[i][j] = A[i][j]/A[i][i]
    b[i] = b[i]/A[i][i]
    x[i] = b[i]

  for k in range(1, iteracao):
    for i in range(0, n):
      soma = 0
      for j in range(0, n):
        if i != j:
          soma = soma + A[i][j] * x[j]
      
      v[i] = b[i] - soma
    d = norma(v,x)
    if d <= e:
      return v

    for i in range(0, n):
      x[i] = v[i]

b = [-2,3,-6]
A = [[1,3,1],[5,2,2],[0,6,8]]

e = 0.05

x = jacobi(A, b, e)
print(x)

x0 = [0.7, -1.6, 0.6]
x1 = [0.96, -1.86, 0.94]
d = norma(x1, x0)
print (d)