# -*- coding: utf-8 -*-
"""IntegraçãoNumérica

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U556r3y1QyQFWxycE3U9vmjPRwlc4v_n

**Newton-Cotes (Trapézios repetidos, 1/3 de Simpson repetido, 3/8 de Simpson repetido)**
"""

import numpy as np


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~Trapézios Repetidos~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

def trapeziosRepetidos(f,a,b,m):

  h = (b-a)/m
  itr = f(a,coeficientes) + f(b,coeficientes)
  k = a + h
  for i in range(1,m):
    k = k + h
    itr = 2*f(k,coeficientes) + itr
  itr = (h/2)*itr
  print("\nValor da integral: ", itr)
  return itr


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~1/3 Simpson Repetido~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

def simpsonRepetido13(f,a,b,m):

  h = (b-a)/m
  itr = f(a,coeficientes) + f(b,coeficientes)
  k = a + h
  for i in range(1,m):
    k = k + h 
    if i%2 == 0:
      itr = 2*f(k,coeficientes) + itr
    else:
      itr = 4*f(k,coeficientes) + itr
  itr = (h/3)*itr
  print("\nValor da integral: ", itr)
  return itr
    

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~3/8 Simpson Repetido~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

def simpsonRepetido38(f,a,b,m):

  h = (b-a)/m
  itr = f(a,coeficientes) + f(b,coeficientes)
  k = a + h
  for i in range(1,m):
    k = k + h    
    if i%3 == 0:
      itr = 2*f(k,coeficientes) + itr
    else:
      itr = 3*f(k,coeficientes) + itr
  itr = 3*(h/8)*itr
  print("\nValor da integral: ", itr)
  return itr

"""**Gerador de polinômios e Menu de opções**"""

import math
import sys
import numpy as np


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~Polinômio~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

grau = int(input("\nInforme o grau do polinômio: "))
n = int(grau+1)
coeficientes = []
for i in range(n,0,-1):
  coeficientes.insert(0, int(input(f'\nDigite o coeficiente para o X^{i-1}:')))

def f(x,coeficientes):

  return sum(c*x**e for (e,c) in enumerate(coeficientes))


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~Intervalos~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

print("\nIntervalos:")
a = int(input("informe o valor de a: "))
b = int(input("informe o valor de b: "))


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~Menu~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

op = True
while op:
  while op:
    metodo = int(input('\nInforme o método que deseja utilizar:\n[1]-Trapézios Repetidos\n[2]-1/3 Simpson Repetido\n[3]-3/8 Simpson Repetido\n[0]-Sair do programa\n'))
    if metodo == 1:
      m = int(input("Informe o número dos subintervalos: "))
      trapeziosRepetidos(f,a,b,m)
      break   
    if metodo == 2:
      while op:
        m = int(input("Informe o número dos subintervalos: "))
        if m%2 != 0:
          print("\nOpção inválida!\n")
          print("Os subintervalos precisam ser multiplos de 2 (2,4,6,8...). Tente novamente!\n")
        else:
          simpsonRepetido13(f,a,b,m)
          break

    if metodo == 3:
      while op:
        m = int(input("Informe o número dos subintervalos: "))
        if m%3 != 0:
          print("\nOpção inválida!\n")
          print("Os subintervalos precisam ser multiplos de 3 (3,6,9,12...). Tente novamente!\n")
        else:
          simpsonRepetido38(f,a,b,m)
          break

    if metodo == 0:
      print("\nPrograma encerrado!\n\n")
      sys.exit(0)

  else:
    print("\nOpção inválida! Tente outra novamente!")